apiVersion: v1
kind: ReplicationController
metadata: 
  name: rcsise
spec:
  replicas:
  selector:
    app: size
  template:
    metadata:
      name: somename
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: hshar/webapp
        ports:
        -containerPort: 9876